apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-api
  namespace: taskflow-prod
spec:
  replicas: 3
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: taskflow-api
  template:
    metadata:
      labels:
        app: taskflow-api
    spec:
      containers:
        - name: taskflow-api
          #image: registry.gitlab.com/haidarra-devops/week-9-devops-taskflow/taskflow-api:latest
          #image: hashicorp/http-echo:latest
          image: REGISTRY_IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8080